server:
  port: 8081
  servlet:
    context-path: /yuxiang-server/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yuxiang?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    path: D:/log/yuxiang-server
  config: classpath:conf/logback-spring.xml
