dubbo:
  application:
    name: yuxiang-server #应用名
  registry:
    address: zookeeper://localhost #zookeeper地址
    port: 2181 #提供注册的端口
  protocol:
    name: dubbo
    port: 20880 #dubbo服务暴露的端口
  scan:
    base-packages: com.yuxiang.server.remoteserver #扫描的包名

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yuxiang?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    path: D:/log/yuxiang-server
  config: classpath:conf/logback-spring.xml
